#docker-compose.prod.yml

version: '3.9'

services:
  web:
    build: ./app
    command: gunicorn DdjangoProject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    environment:
      - DB_HOST=rc1a-qwdydbxcnzc37yim.mdb.yandexcloud.net
      - DB_NAME=db
      - DB_USER=user1
      - DB_PASSWORD=12345678
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=user1
      - POSTGRES_DB=db1

volumes:
  postgres_data: