version: '3.9'

services:
  postgres:
    image: postgres:16
    ports:
      - 6432:6432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=user1
      - POSTGRES_DB=db1
  django:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 158.160.46.23:8000
    depends_on:
      - postgres
    environment:
      - DB_HOST=rc1a-qwdydbxcnzc37yim.mdb.yandexcloud.net
      - DB_NAME=db
      - DB_USER=user1
      - DB_PASSWORD=12345678