# Generated by Django 5.0 on 2024-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('BYR', models.FloatField(verbose_name='BYR')),
                ('USD', models.FloatField(verbose_name='USD')),
                ('EUR', models.FloatField(verbose_name='EUR')),
                ('KZT', models.FloatField(verbose_name='KZT')),
                ('UAH', models.FloatField(verbose_name='UAH')),
                ('AZN', models.FloatField(verbose_name='AZN')),
                ('KGS', models.FloatField(verbose_name='KGS')),
                ('UZS', models.FloatField(verbose_name='UZS')),
                ('GEL', models.FloatField(verbose_name='GEL')),
            ],
        ),
    ]
